# -*- coding: utf-8 -*-
"""plotting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1187RrKhoxP_e0vm-dRZckByhQ-A4HKz1
"""

import matplotlib.pyplot as plt

def plot_history(train_loss_list,val_loss_list,name):
  plt.plot(train_loss_list, label='Training Loss',color='blue', linestyle='-', marker='o')
  plt.plot(val_loss_list, label='Validation Loss',color='orange', linestyle='-', marker='o')
  plt.xlabel('Epoch')
  plt.ylabel('Loss')
  plt.title(f'{name}')
  plt.legend()
  plt.grid(True)

  plt.show()
  plt.close()